/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject3;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.time.Clock;
import java.time.ZoneId;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kfergu10
 */
public class JTableData extends javax.swing.JFrame {
 final String ID = "kfergu10";
        final String PW = "COSC*2kc9l";
        final String SERVER = "jdbc:mysql://triton.towson.edu:3360/?serverTimezone=EST#/kfergu10db?useSSL=false";
        //String querys;
    /**
     * Creates new form JTableData
     */
    public JTableData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        UpdateDivButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtDivID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHeadSSN = new javax.swing.JTextField();
        InsertDivButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BranchTab = new javax.swing.JMenu();
        DeptTab = new javax.swing.JMenu();
        PatDivTab = new javax.swing.JMenu();
        TrademarkDivTab = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Show Table Values");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        UpdateDivButton.setText("Update Division Info");
        UpdateDivButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDivButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Div_ID_f", "Head_SSN_f"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtDivID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDivIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Div_ID_f");

        jLabel2.setText("Head_SSN_f");

        txtHeadSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeadSSNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDivID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeadSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDivID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHeadSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        InsertDivButton.setText("Insert Division Info");
        InsertDivButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertDivButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Delete Division Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Filters");

        jButton4.setText("Division Heads");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");

        jButton3.setText("Division ID");

        jMenu1.setText("Main Menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        BranchTab.setText("Branches");
        BranchTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BranchTabMouseClicked(evt);
            }
        });
        jMenuBar1.add(BranchTab);

        DeptTab.setText("Departments");
        DeptTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptTabActionPerformed(evt);
            }
        });
        jMenuBar1.add(DeptTab);

        PatDivTab.setText("Patent Division");
        PatDivTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatDivTabMouseClicked(evt);
            }
        });
        PatDivTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatDivTabActionPerformed(evt);
            }
        });
        jMenuBar1.add(PatDivTab);

        TrademarkDivTab.setText("Trademark Divison");
        TrademarkDivTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrademarkDivTabMouseClicked(evt);
            }
        });
        jMenuBar1.add(TrademarkDivTab);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UpdateDivButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InsertDivButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(UpdateDivButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertDivButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(188, 188, 188))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateDivButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDivButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount() == 1){
            String Div_ID = txtDivID.getText();
            String Head_SSN =txtHeadSSN.getText();
            
            tblModel.setValueAt(Div_ID, jTable1.getSelectedRow(), 0);
            tblModel.setValueAt(Head_SSN, jTable1.getSelectedRow(), 1);
            
             
        
        
            // querys = "UPDATE kfergu10db.Employees SET Email_f = 'c@gmail.com' WHERE Emp_SSN_f = '123123123';";
        

            JOptionPane.showMessageDialog(this, "Update Successful");

        }
        else{
            if(jTable1.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Table is Empty");
                
            }
            else{
            JOptionPane.showMessageDialog(this, "Please Select a Single Row");
                
            }
        }
        
        
       // Update_Employee ue = new Update_Employee();
        //ue.show();
       // dispose();
    }//GEN-LAST:event_UpdateDivButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(SERVER, ID, PW);

            Statement st = con.createStatement();
            String sql = "Select * From kfergu10db.Divisions";
            ResultSet rs = st.executeQuery(sql);

            while(rs.next()){
                String DivID = String.valueOf(rs.getInt("Div_ID_f"));
                String HeadSSN = String.valueOf(rs.getInt("Head_SSN_f"));

                String tbData[] = {DivID, HeadSSN};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbData);
            }
            con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        JTableData jtd = new JTableData();
        jtd.show();
        dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void txtDivIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDivIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDivIDActionPerformed

    private void txtHeadSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeadSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeadSSNActionPerformed

    private void InsertDivButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertDivButtonActionPerformed
        // TODO add your handling code here:
if(txtDivID.getText().equals("")|| txtHeadSSN.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Please Enter Div ID and Head SSN");
}
else{
    String data[]= {txtDivID.getText(), txtHeadSSN.getText()};
    DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
    tblModel.addRow(data);
    
    
        String querys, Div_ID, Head_SSN;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            Div_ID = tblModel.getValueAt(tblModel.getRowCount(), 0).toString();
            Head_SSN = tblModel.getValueAt(tblModel.getRowCount(), 1).toString();
            try{
            querys = "INSERT INTO kfergu10db.Divisions(Div_ID_f, Head_SSN_f)values (?,?)";
            PreparedStatement prepstmt = con.prepareStatement(querys);
            prepstmt.setString(1, Div_ID);
            prepstmt.setString(2, Head_SSN);
            prepstmt.execute();
            }
            catch(SQLException e){
                System.out.println(e.getMessage());
            }
           
            JOptionPane.showMessageDialog(this, "Data inserted Sucescully");
        }
        catch(Exception e){
             System.out.println(e.getMessage());
        }

}
    }//GEN-LAST:event_InsertDivButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        String Div_ID= tblModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String Head_SSN= tblModel.getValueAt(jTable1.getSelectedRow(), 1).toString();

        txtDivID.setText(Div_ID);
        txtHeadSSN.setText(Head_SSN);

        JOptionPane.showMessageDialog(this, "Data Successfully Inserted");
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        MainMenu mm = new MainMenu();
        mm.show();
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void BranchTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BranchTabMouseClicked
        // TODO add your handling code here:
        Branches brch = new Branches();
        brch.show();
        dispose();
        
    }//GEN-LAST:event_BranchTabMouseClicked

    private void DeptTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptTabActionPerformed
        // TODO add your handling code here:
        Departments dept = new Departments();
        dept.show();
        dispose();
    }//GEN-LAST:event_DeptTabActionPerformed

    private void PatDivTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatDivTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatDivTabActionPerformed

    private void PatDivTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatDivTabMouseClicked
        // TODO add your handling code here:
        PatentDiv pd = new PatentDiv();
        pd.show();
        dispose();
    }//GEN-LAST:event_PatDivTabMouseClicked

    private void TrademarkDivTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrademarkDivTabMouseClicked
        // TODO add your handling code here:
        TrademarkDiv td = new TrademarkDiv();
        td.show();
        dispose();
    }//GEN-LAST:event_TrademarkDivTabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTableData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTableData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTableData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTableData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTableData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BranchTab;
    private javax.swing.JMenu DeptTab;
    private javax.swing.JButton InsertDivButton;
    private javax.swing.JMenu PatDivTab;
    private javax.swing.JMenu TrademarkDivTab;
    private javax.swing.JButton UpdateDivButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDivID;
    private javax.swing.JTextField txtHeadSSN;
    // End of variables declaration//GEN-END:variables
}
